/* GENERATED FILE — DO NOT EDIT.
 *
 * Source: design/cards.yaml       Regenerate: node tools/cards.mjs build
 * Check:  node tools/cards.mjs check
 *
 * Every card in North vs Up, as printed, with each room's threshold outcomes and
 * Flee line already parsed into structure.  Data, not rules: this module knows
 * what a card says and nothing about what the engine does with it.
 *
 * EVERY NUMBER IS A PLACEHOLDER — costs, stats and thresholds are still open
 * design (design/rulebook.md, "NOT YET RULED").
 */

import type { CardContent } from "../domain/printed";

export const CARD_CONTENT = {
  meta: {
    updated: "2026-09-16",
  },
  cards: [
    {
      name: "Shove",
      set: "official",
      kind: "player",
      owner: "Red",
      rarity: null,
      starter: true,
      count: 5,
      cost: 1,
      oomph: 2,
      scramble: 0,
      conditionalStat: false,
      text: "",
    },
    {
      name: "Charge In",
      set: "official",
      kind: "player",
      owner: "Red",
      rarity: null,
      starter: true,
      count: 5,
      cost: 2,
      oomph: 4,
      scramble: 0,
      conditionalStat: false,
      text: "",
    },
    {
      name: "Overdrive",
      set: "official",
      kind: "player",
      owner: "Red",
      rarity: null,
      starter: true,
      count: 2,
      cost: 0,
      oomph: 2,
      scramble: 0,
      conditionalStat: false,
      text: "Exhaust 2 (the top 2 cards of your deck go to your Exhaust pile).",
    },
    {
      name: "Duck Under",
      set: "official",
      kind: "player",
      owner: "Gray",
      rarity: null,
      starter: true,
      count: 5,
      cost: 1,
      oomph: 0,
      scramble: 2,
      conditionalStat: false,
      text: "",
    },
    {
      name: "Pick The Lock",
      set: "official",
      kind: "player",
      owner: "Gray",
      rarity: null,
      starter: true,
      count: 5,
      cost: 2,
      oomph: 0,
      scramble: 4,
      conditionalStat: false,
      text: "",
    },
    {
      name: "Peek Around Corner",
      set: "official",
      kind: "player",
      owner: "Gray",
      rarity: null,
      starter: true,
      count: 2,
      cost: 1,
      oomph: 0,
      scramble: 1,
      conditionalStat: false,
      text: "Look at the top card of any deck, then put it back on top. (Peek 1?)",
    },
    {
      name: "Reckless Swing",
      set: "proposed",
      kind: "player",
      owner: "Red",
      rarity: "Fine",
      starter: false,
      count: 1,
      cost: 1,
      oomph: 4,
      scramble: 0,
      conditionalStat: false,
      text: "Exhaust 1.",
    },
    {
      name: "Fast Follow",
      set: "proposed",
      kind: "player",
      owner: "Red",
      rarity: "Fine",
      starter: false,
      count: 1,
      cost: 1,
      oomph: 3,
      scramble: 0,
      conditionalStat: false,
      text: "If Gray played a card this turn, this costs 0.",
    },
    {
      name: "Reckless",
      set: "proposed",
      kind: "player",
      owner: "Red",
      rarity: "Fine",
      starter: false,
      count: 1,
      cost: 1,
      oomph: 5,
      scramble: 0,
      conditionalStat: false,
      text: "Exhaust 3.",
    },
    {
      name: "Second Wind",
      set: "proposed",
      kind: "player",
      owner: "Red",
      rarity: "Cool",
      starter: false,
      count: 1,
      cost: 2,
      oomph: 4,
      scramble: 0,
      conditionalStat: false,
      text: "Shuffle a Red card from your discard pile back into your deck.",
    },
    {
      name: "Junk Launcher",
      set: "proposed",
      kind: "player",
      owner: "Red",
      rarity: "Cool",
      starter: false,
      count: 1,
      cost: 2,
      oomph: 2,
      scramble: 0,
      conditionalStat: false,
      text: "This has Oomph +2 for each card you paid with this turn.",
    },
    {
      name: "Heavy Pockets",
      set: "proposed",
      kind: "player",
      owner: "Red",
      rarity: "Cool",
      starter: false,
      count: 1,
      cost: 1,
      oomph: 2,
      scramble: 0,
      conditionalStat: false,
      text: "Shuffle 1 Stuff from your hand into your deck.",
    },
    {
      name: "Deadweight Grip",
      set: "proposed",
      kind: "player",
      owner: "Red",
      rarity: "Woah",
      starter: false,
      count: 1,
      cost: 1,
      oomph: 0,
      scramble: 2,
      conditionalStat: false,
      text: "Holding: Cards you play have +1 Oomph, but you may not draw more than 2 cards per turn.",
    },
    {
      name: "Both Barrels",
      set: "proposed",
      kind: "player",
      owner: "Red",
      rarity: "Woah",
      starter: false,
      count: 1,
      cost: 2,
      oomph: 4,
      scramble: 0,
      conditionalStat: false,
      text: "If Gray has already played at least one card this turn, +2 Oomph. If the room is Cleared, return this to your hand at the end of the turn.",
    },
    {
      name: "Flurry",
      set: "proposed",
      kind: "player",
      owner: "Red",
      rarity: "Woah",
      starter: false,
      count: 1,
      cost: 1,
      oomph: 0,
      scramble: 0,
      conditionalStat: true,
      text: "Oomph equal to twice the number of other cards Red played this turn.",
    },
    {
      name: "Zen Mode",
      set: "proposed",
      kind: "player",
      owner: "Red",
      rarity: "Woah",
      starter: false,
      count: 1,
      cost: 0,
      oomph: 0,
      scramble: 0,
      conditionalStat: false,
      text: "Holding: you don't `Exhaust`.",
    },
    {
      name: "Catch Your Breath",
      set: "proposed",
      kind: "player",
      owner: "Gray",
      rarity: "Fine",
      starter: false,
      count: 1,
      cost: 1,
      oomph: 0,
      scramble: 1,
      conditionalStat: false,
      text: "Look at the top 2 cards of any deck. Put them back in either order.",
    },
    {
      name: "In Step",
      set: "proposed",
      kind: "player",
      owner: "Gray",
      rarity: "Cool",
      starter: false,
      count: 1,
      cost: 1,
      oomph: 0,
      scramble: 0,
      conditionalStat: true,
      text: "Oomph equal to twice the number of cards Red has played this turn.",
    },
    {
      name: "One Man's Junk",
      set: "proposed",
      kind: "player",
      owner: "Gray",
      rarity: "Cool",
      starter: false,
      count: 1,
      cost: 1,
      oomph: 0,
      scramble: 0,
      conditionalStat: true,
      text: "If any Bad Stuff is played this turn, Oomph 2 and Scramble 2.",
    },
    {
      name: "Hack the Doors",
      set: "proposed",
      kind: "player",
      owner: "Gray",
      rarity: "Cool",
      starter: false,
      count: 1,
      cost: 1,
      oomph: 0,
      scramble: 2,
      conditionalStat: false,
      text: "Look at the top 3 cards of any deck, then put them back in any order.",
    },
    {
      name: "Here, Catch",
      set: "proposed",
      kind: "player",
      owner: "Gray",
      rarity: "Fine",
      starter: false,
      count: 1,
      cost: 1,
      oomph: 0,
      scramble: 2,
      conditionalStat: false,
      text: "Move 1 Stuff from your hand to Red's hand.",
    },
    {
      name: "Hit 'n Run",
      set: "proposed",
      kind: "player",
      owner: "Gray",
      rarity: "Fine",
      starter: false,
      count: 1,
      cost: 1,
      oomph: 2,
      scramble: 0,
      conditionalStat: false,
      text: "Shuffle a Gray card from your discard pile back into your deck.",
    },
    {
      name: "I'll Take That",
      set: "proposed",
      kind: "player",
      owner: "Gray",
      rarity: "Fine",
      starter: false,
      count: 1,
      cost: 1,
      oomph: 0,
      scramble: 2,
      conditionalStat: false,
      text: "Shuffle 1 Stuff from Red's hand into Red's deck.",
    },
    {
      name: "Covering Fire",
      set: "proposed",
      kind: "player",
      owner: "Gray",
      rarity: "Cool",
      starter: false,
      count: 1,
      cost: 1,
      oomph: 0,
      scramble: 2,
      conditionalStat: false,
      text: "Every time Red plays a card this turn, draw 1 card.",
    },
    {
      name: "Every Little Bit Helps",
      set: "proposed",
      kind: "player",
      owner: "Gray",
      rarity: "Woah",
      starter: false,
      count: 1,
      cost: 1,
      oomph: 0,
      scramble: 0,
      conditionalStat: true,
      text: "Scramble equal to twice the number of other cards Gray played this turn.",
    },
    {
      name: "Level Up",
      set: "proposed",
      kind: "player",
      owner: "Gray",
      rarity: "Woah",
      starter: false,
      count: 1,
      cost: 2,
      oomph: 0,
      scramble: 0,
      conditionalStat: false,
      text: "Scrap a card from your hand. If you do, draw the top card from the Gray Rewards deck directly into your hand.",
    },
    {
      name: "I Know Kung Fu",
      set: "proposed",
      kind: "player",
      owner: "Gray",
      rarity: "Woah",
      starter: false,
      count: 1,
      cost: 3,
      oomph: 5,
      scramble: 0,
      conditionalStat: false,
      text: "Holding: when you play a card with Scramble, draw 1 card.",
    },
    {
      name: "Pry Bar",
      set: "proposed",
      kind: "good_stuff",
      owner: null,
      rarity: "Fine",
      starter: false,
      count: 1,
      cost: 0,
      oomph: 3,
      scramble: 0,
      conditionalStat: false,
      text: "",
    },
    {
      name: "Coil Of Cable",
      set: "proposed",
      kind: "good_stuff",
      owner: null,
      rarity: "Fine",
      starter: false,
      count: 1,
      cost: 0,
      oomph: 0,
      scramble: 3,
      conditionalStat: false,
      text: "",
    },
    {
      name: "Crowbar",
      set: "proposed",
      kind: "good_stuff",
      owner: null,
      rarity: "Fine",
      starter: false,
      count: 1,
      cost: 0,
      oomph: 1,
      scramble: 1,
      conditionalStat: false,
      text: "Play: if you get any Good Stuff this turn, get an additional one.",
    },
    {
      name: "A Pair Of Stich-Em-Ups",
      set: "proposed",
      kind: "good_stuff",
      owner: null,
      rarity: "Cool",
      starter: false,
      count: 1,
      cost: 1,
      oomph: 0,
      scramble: 0,
      conditionalStat: false,
      text: "Choose a character. Move 2 cards from that character's discard pile to the bottom of their deck.",
    },
    {
      name: "Cutting Torch",
      set: "proposed",
      kind: "good_stuff",
      owner: null,
      rarity: "Cool",
      starter: false,
      count: 1,
      cost: 2,
      oomph: 5,
      scramble: 0,
      conditionalStat: false,
      text: "",
    },
    {
      name: "Grav Harness",
      set: "proposed",
      kind: "good_stuff",
      owner: null,
      rarity: "Woah",
      starter: false,
      count: 1,
      cost: 2,
      oomph: 3,
      scramble: 3,
      conditionalStat: false,
      text: "One of you draws 1 card, (even if their hand is full).",
    },
    {
      name: "Riot Shield",
      set: "proposed",
      kind: "good_stuff",
      owner: null,
      rarity: "Cool",
      starter: false,
      count: 1,
      cost: 1,
      oomph: 0,
      scramble: 3,
      conditionalStat: false,
      text: "If the room is Cleared, return this to your hand at the end of the turn.",
    },
    {
      name: "Overcharged Battery",
      set: "proposed",
      kind: "good_stuff",
      owner: null,
      rarity: "Cool",
      starter: false,
      count: 1,
      cost: 1,
      oomph: 2,
      scramble: 0,
      conditionalStat: false,
      text: "The next card played this turn costs 0.",
    },
    {
      name: "Faceful Of Slime",
      set: "proposed",
      kind: "bad_stuff",
      owner: null,
      rarity: null,
      starter: false,
      count: 1,
      cost: 2,
      oomph: 0,
      scramble: 0,
      conditionalStat: false,
      text: "Holding: you may not draw more than 1 card per turn.",
    },
    {
      name: "Torn Seal",
      set: "proposed",
      kind: "bad_stuff",
      owner: null,
      rarity: null,
      starter: false,
      count: 1,
      cost: 2,
      oomph: 0,
      scramble: 0,
      conditionalStat: false,
      text: "",
    },
    {
      name: "Sluggish",
      set: "proposed",
      kind: "bad_stuff",
      owner: null,
      rarity: null,
      starter: false,
      count: 1,
      cost: 1,
      oomph: 0,
      scramble: 0,
      conditionalStat: false,
      text: "Holding: cards cost +1 to play.",
    },
    {
      name: "Rust",
      set: "proposed",
      kind: "bad_stuff",
      owner: null,
      rarity: null,
      starter: false,
      count: 1,
      cost: 2,
      oomph: 0,
      scramble: 0,
      conditionalStat: false,
      text: "Holding: Stuff you play has -1 Oomph.",
    },
    {
      name: "Spore Cloud",
      set: "proposed",
      kind: "bad_stuff",
      owner: null,
      rarity: null,
      starter: false,
      count: 1,
      cost: 2,
      oomph: 0,
      scramble: 0,
      conditionalStat: false,
      text: "Holding: You can't have more than 3 cards in your hand.",
    },
    {
      name: "Panic",
      set: "proposed",
      kind: "bad_stuff",
      owner: null,
      rarity: null,
      starter: false,
      count: 1,
      cost: 1,
      oomph: 0,
      scramble: 0,
      conditionalStat: false,
      text: "Holding: ALL rooms require an additional 2 `Scramble` to clear. Play: Exhaust 2.",
    },
    {
      name: "My Head Is Quantum Spinning",
      set: "proposed",
      kind: "bad_stuff",
      owner: null,
      rarity: null,
      starter: false,
      count: 1,
      cost: 1,
      oomph: 0,
      scramble: 0,
      conditionalStat: false,
      text: "Holding: whenever you draw a card, your partner must also draw a card.",
    },
  ],
  rooms: [
    {
      name: "Gross Thing That Looks Like A Cherry",
      set: "proposed",
      kind: "enemy",
      floor: 1,
      count: 1,
      thresholds: [
        {
          stat: "Oomph",
          value: 5,
          outcome: "Ascend",
          clears: true,
          fleeFree: false,
          ascends: true,
          effects: [],
        },
      ],
      flee: {
        text: "Both of you Exhaust 1.",
        clears: false,
        effects: [
          {
            type: "ExhaustFromDeck",
            who: "both",
            amount: 1,
          },
        ],
      },
    },
    {
      name: "Coney, The Thing In The Stairwell",
      set: "proposed",
      kind: "enemy",
      floor: 2,
      count: 1,
      thresholds: [
        {
          stat: "Oomph",
          value: 9,
          outcome: "Ascend",
          clears: true,
          fleeFree: false,
          ascends: true,
          effects: [],
        },
      ],
      flee: {
        text: "Both of you Exhaust 1.",
        clears: false,
        effects: [
          {
            type: "ExhaustFromDeck",
            who: "both",
            amount: 1,
          },
        ],
      },
    },
    {
      name: "Villy, Coney's Work Husband",
      set: "proposed",
      kind: "enemy",
      floor: 3,
      count: 1,
      thresholds: [
        {
          stat: "Oomph",
          value: 9,
          outcome: "Ascend",
          clears: true,
          fleeFree: false,
          ascends: true,
          effects: [],
        },
        {
          stat: "Scramble",
          value: 9,
          outcome: "Flee this room for free.",
          clears: false,
          fleeFree: true,
          ascends: false,
          effects: [],
        },
      ],
      flee: {
        text: "Both of you Exhaust 2.",
        clears: false,
        effects: [
          {
            type: "ExhaustFromDeck",
            who: "both",
            amount: 2,
          },
        ],
      },
    },
    {
      name: "Collapsed Stairwell",
      set: "proposed",
      kind: "hazard",
      floor: null,
      count: 3,
      thresholds: [
        {
          stat: "Scramble",
          value: 2,
          outcome: "Clear, but both of you Exhaust 1.",
          clears: true,
          fleeFree: false,
          ascends: false,
          effects: [
            {
              type: "ExhaustFromDeck",
              who: "both",
              amount: 1,
            },
          ],
        },
        {
          stat: "Scramble",
          value: 5,
          outcome: "Clear, and one of you reveals a reward.",
          clears: true,
          fleeFree: false,
          ascends: false,
          effects: [
            {
              type: "RevealReward",
              who: "one",
            },
          ],
        },
      ],
      flee: {
        text: "One of you Exhausts 3.",
        clears: false,
        effects: [
          {
            type: "ExhaustFromDeck",
            who: "one",
            amount: 3,
          },
        ],
      },
    },
    {
      name: "Ruptured Coolant Line",
      set: "proposed",
      kind: "hazard",
      floor: null,
      count: 3,
      thresholds: [
        {
          stat: "Scramble",
          value: 4,
          outcome: "Clear, but both of you get Bad Stuff.",
          clears: true,
          fleeFree: false,
          ascends: false,
          effects: [
            {
              type: "DealBadStuff",
              who: "both",
            },
          ],
        },
        {
          stat: "Scramble",
          value: 7,
          outcome: "Clear, and one of you reveals a reward.",
          clears: true,
          fleeFree: false,
          ascends: false,
          effects: [
            {
              type: "RevealReward",
              who: "one",
            },
          ],
        },
      ],
      flee: {
        text: "Both of you Exhaust 1, and one of you gets Bad Stuff.",
        clears: false,
        effects: [
          {
            type: "ExhaustFromDeck",
            who: "both",
            amount: 1,
          },
          {
            type: "DealBadStuff",
            who: "one",
          },
        ],
      },
    },
    {
      name: "Sorting Room",
      set: "proposed",
      kind: "stuff",
      floor: null,
      count: 3,
      thresholds: [
        {
          stat: "Oomph",
          value: 2,
          outcome: "Red gets Good Stuff.",
          clears: true,
          fleeFree: false,
          ascends: false,
          effects: [
            {
              type: "TakeGoodStuff",
              who: "Red",
              count: 1,
            },
          ],
        },
        {
          stat: "Scramble",
          value: 2,
          outcome: "Gray gets Good Stuff.",
          clears: true,
          fleeFree: false,
          ascends: false,
          effects: [
            {
              type: "TakeGoodStuff",
              who: "Gray",
              count: 1,
            },
          ],
        },
      ],
      flee: {
        text: "Leave empty-handed.",
        clears: false,
        effects: [],
      },
    },
    {
      name: "Ration Locker",
      set: "proposed",
      kind: "stuff",
      floor: null,
      count: 2,
      thresholds: [
        {
          stat: "Oomph",
          value: 2,
          outcome: "Red gets Good Stuff.",
          clears: true,
          fleeFree: false,
          ascends: false,
          effects: [
            {
              type: "TakeGoodStuff",
              who: "Red",
              count: 1,
            },
          ],
        },
        {
          stat: "Scramble",
          value: 2,
          outcome: "Gray gets Good Stuff.",
          clears: true,
          fleeFree: false,
          ascends: false,
          effects: [
            {
              type: "TakeGoodStuff",
              who: "Gray",
              count: 1,
            },
          ],
        },
        {
          stat: "Oomph",
          value: 4,
          outcome: "Red gets 2 instead.",
          clears: true,
          fleeFree: false,
          ascends: false,
          effects: [
            {
              type: "TakeGoodStuff",
              who: "Red",
              count: 2,
            },
          ],
        },
        {
          stat: "Scramble",
          value: 4,
          outcome: "Gray gets 2 instead.",
          clears: true,
          fleeFree: false,
          ascends: false,
          effects: [
            {
              type: "TakeGoodStuff",
              who: "Gray",
              count: 2,
            },
          ],
        },
      ],
      flee: {
        text: "Leave empty-handed.",
        clears: false,
        effects: [],
      },
    },
    {
      name: "Tool Cage",
      set: "proposed",
      kind: "stuff",
      floor: null,
      count: 2,
      thresholds: [
        {
          stat: "Scramble",
          value: 3,
          outcome: "Both of you get Good Stuff.",
          clears: true,
          fleeFree: false,
          ascends: false,
          effects: [
            {
              type: "TakeGoodStuff",
              who: "both",
              count: 1,
            },
          ],
        },
        {
          stat: "Oomph",
          value: 5,
          outcome: "Red gets 2 instead.",
          clears: true,
          fleeFree: false,
          ascends: false,
          effects: [
            {
              type: "TakeGoodStuff",
              who: "Red",
              count: 2,
            },
          ],
        },
      ],
      flee: {
        text: "Leave empty-handed.",
        clears: false,
        effects: [],
      },
    },
    {
      name: "Spill Of Cargo",
      set: "proposed",
      kind: "stuff",
      floor: null,
      count: 2,
      thresholds: [
        {
          stat: "Scramble",
          value: 3,
          outcome: "Both of you get Good Stuff.",
          clears: true,
          fleeFree: false,
          ascends: false,
          effects: [
            {
              type: "TakeGoodStuff",
              who: "both",
              count: 1,
            },
          ],
        },
        {
          stat: "Scramble",
          value: 5,
          outcome: "Gray gets 2 instead.",
          clears: true,
          fleeFree: false,
          ascends: false,
          effects: [
            {
              type: "TakeGoodStuff",
              who: "Gray",
              count: 2,
            },
          ],
        },
      ],
      flee: {
        text: "Leave empty-handed.",
        clears: false,
        effects: [],
      },
    },
  ],
} as const satisfies CardContent;
