/* GENERATED FILE — DO NOT EDIT.
 *
 * Source: design/cards.yaml       Regenerate: node tools/cards.mjs build
 * Check:  node tools/cards.mjs check
 *
 * Every card in North vs Up, as printed, with each room's threshold outcomes and
 * Flee line already parsed into structure.  Data, not rules: this module knows
 * what a card says and nothing about what the engine does with it.
 *
 * EVERY NUMBER IS A PLACEHOLDER — costs, stats and thresholds are still open
 * design (design/rulebook.md, "NOT YET RULED").
 */

import type { CardContent } from "../domain/printed";

export const CARD_CONTENT = {
  meta: {"updated":"2026-09-23"},
  cards: [
    {"name":"Shove","set":"official","kind":"player","owner":"Red","rarity":null,"starter":true,"count":4,"cost":1,"oomph":2,"scramble":0,"conditionalStat":false,"text":"","flavor":"A quick, decisive shove to clear space."},
    {"name":"Charge In","set":"official","kind":"player","owner":"Red","rarity":null,"starter":true,"count":5,"cost":2,"oomph":4,"scramble":0,"conditionalStat":false,"text":"","flavor":"Lower your shoulder and put your full momentum into it."},
    {"name":"Lean In","set":"proposed","kind":"player","owner":"Red","rarity":null,"starter":true,"count":1,"cost":1,"oomph":1,"scramble":1,"conditionalStat":false,"text":"","flavor":"Put your weight into helping Gray slip past."},
    {"name":"Overdrive","set":"official","kind":"player","owner":"Red","rarity":null,"starter":true,"count":2,"cost":0,"oomph":2,"scramble":0,"conditionalStat":false,"text":"Exhaust 2.","flavor":"Burn extra stamina for an immediate burst."},
    {"name":"Duck Under","set":"official","kind":"player","owner":"Gray","rarity":null,"starter":true,"count":4,"cost":1,"oomph":0,"scramble":2,"conditionalStat":false,"text":"","flavor":"Stay low and keep moving."},
    {"name":"Pick The Lock","set":"official","kind":"player","owner":"Gray","rarity":null,"starter":true,"count":5,"cost":2,"oomph":0,"scramble":4,"conditionalStat":false,"text":"","flavor":"Pop the pins before anyone notices you're there."},
    {"name":"Work The Angles","set":"proposed","kind":"player","owner":"Gray","rarity":null,"starter":true,"count":1,"cost":1,"oomph":1,"scramble":1,"conditionalStat":false,"text":"","flavor":"Find the structural weak point so Red can strike."},
    {"name":"Peek Around Corner","set":"official","kind":"player","owner":"Gray","rarity":null,"starter":true,"count":2,"cost":1,"oomph":0,"scramble":1,"conditionalStat":false,"text":"Peek 1.","flavor":"A quick glance ahead to spot hazards."},
    {"name":"Reckless Swing","set":"proposed","kind":"player","owner":"Red","rarity":"Fine","starter":false,"count":3,"cost":1,"oomph":4,"scramble":0,"conditionalStat":false,"text":"Exhaust 1.","flavor":"Put everything into a wide arc, damn the recoil."},
    {"name":"Fast Follow","set":"proposed","kind":"player","owner":"Red","rarity":"Fine","starter":false,"count":3,"cost":1,"oomph":3,"scramble":0,"conditionalStat":false,"text":"If Gray played a card this turn, play this card for free.","flavor":"Stepping right into the opening Gray created."},
    {"name":"Reckless","set":"proposed","kind":"player","owner":"Red","rarity":"Fine","starter":false,"count":2,"cost":1,"oomph":5,"scramble":0,"conditionalStat":false,"text":"Exhaust 3.","flavor":"Pure raw force that leaves you completely breathless."},
    {"name":"Bull Rush","set":"proposed","kind":"player","owner":"Red","rarity":"Fine","starter":false,"count":2,"cost":1,"oomph":2,"scramble":1,"conditionalStat":false,"text":"","flavor":"Charge ahead while keeping your footing on loose debris."},
    {"name":"Cross Punch","set":"proposed","kind":"player","owner":"Red","rarity":"Fine","starter":false,"count":2,"cost":2,"oomph":4,"scramble":2,"conditionalStat":false,"text":"Exhaust 1.","flavor":"A heavy two-part combination attack."},
    {"name":"Second Wind","set":"proposed","kind":"player","owner":"Red","rarity":"Cool","starter":false,"count":2,"cost":2,"oomph":4,"scramble":0,"conditionalStat":false,"text":"Shuffle a Red card from your Exhaust pile into your deck.","flavor":"Catch your breath and shake off the fatigue."},
    {"name":"Junk Launcher","set":"proposed","kind":"player","owner":"Red","rarity":"Cool","starter":false,"count":2,"cost":2,"oomph":0,"scramble":0,"conditionalStat":true,"text":"Oomph equal to total costs of all cards you played this turn.","flavor":"Hurl whatever scrap isn't nailed down."},
    {"name":"Heavy Pockets","set":"proposed","kind":"player","owner":"Red","rarity":"Cool","starter":false,"count":2,"cost":1,"oomph":2,"scramble":1,"conditionalStat":false,"text":"Shuffle 1 Stuff from your hand into your deck.","flavor":"Stash the heavy salvage where it won't weigh down your swing."},
    {"name":"Tag Team","set":"proposed","kind":"player","owner":"Red","rarity":"Cool","starter":false,"count":2,"cost":1,"oomph":2,"scramble":2,"conditionalStat":false,"text":"If Gray played a card this turn, draw 1 card.","flavor":"Seamless hand-off between partners."},
    {"name":"Catch Your Breath","set":"proposed","kind":"player","owner":"Gray","rarity":"Fine","starter":false,"count":2,"cost":1,"oomph":0,"scramble":2,"conditionalStat":false,"text":"Look at top 2 cards of any deck. Put them back in either order.","flavor":"Pause for a second to read the room."},
    {"name":"Here, Catch","set":"proposed","kind":"player","owner":"Gray","rarity":"Fine","starter":false,"count":2,"cost":1,"oomph":0,"scramble":3,"conditionalStat":false,"text":"Move 1 Stuff from your hand to Red's hand.","flavor":"Toss a heavy tool over before it bogs you down."},
    {"name":"Hit 'n Run","set":"proposed","kind":"player","owner":"Gray","rarity":"Fine","starter":false,"count":2,"cost":1,"oomph":1,"scramble":2,"conditionalStat":false,"text":"Shuffle a Gray card from your Exhaust pile into your deck.","flavor":"Strike fast and disappear into the shadows."},
    {"name":"I'll Take That","set":"proposed","kind":"player","owner":"Gray","rarity":"Fine","starter":false,"count":2,"cost":1,"oomph":0,"scramble":3,"conditionalStat":false,"text":"Shuffle 1 Stuff from Red's hand into Red's deck.","flavor":"Relieve Red of that cumbersome pack."},
    {"name":"Quick Vault","set":"proposed","kind":"player","owner":"Gray","rarity":"Fine","starter":false,"count":2,"cost":1,"oomph":1,"scramble":2,"conditionalStat":false,"text":"","flavor":"Spring off Red's shoulder to clear the gap."},
    {"name":"In Step","set":"proposed","kind":"player","owner":"Gray","rarity":"Cool","starter":false,"count":2,"cost":1,"oomph":0,"scramble":0,"conditionalStat":true,"text":"Scramble equal to 2 times the number of cards Red has played this turn.","flavor":"Sync your movements perfectly with Red's brute rhythm."},
    {"name":"One Man's Junk","set":"proposed","kind":"player","owner":"Gray","rarity":"Cool","starter":false,"count":2,"cost":1,"oomph":2,"scramble":2,"conditionalStat":false,"text":"If any Bad Stuff is played this turn, gain Oomph +1 and Scramble +1.","flavor":"Turn hazardous junk into a makeshift advantage."},
    {"name":"Hack the Doors","set":"proposed","kind":"player","owner":"Gray","rarity":"Cool","starter":false,"count":2,"cost":1,"oomph":0,"scramble":3,"conditionalStat":false,"text":"Look at top 3 cards of any deck, put back in any order.","flavor":"Bypass the security subroutines to peek ahead."},
    {"name":"Covering Fire","set":"proposed","kind":"player","owner":"Gray","rarity":"Cool","starter":false,"count":2,"cost":1,"oomph":0,"scramble":2,"conditionalStat":false,"text":"Every time Red plays a card this turn, draw 1 card.","flavor":"Keep their eyes on you so Red can maneuver freely."},
    {"name":"Distract & Pivot","set":"proposed","kind":"player","owner":"Gray","rarity":"Cool","starter":false,"count":2,"cost":2,"oomph":2,"scramble":3,"conditionalStat":false,"text":"The next card Red plays this turn costs 1 fewer card to play.","flavor":"Create a wide opening for Red to land a massive strike."},
    {"name":"Pry Bar","set":"proposed","kind":"good_stuff","owner":null,"rarity":"Fine","starter":false,"count":3,"cost":0,"oomph":3,"scramble":0,"conditionalStat":false,"text":"","flavor":"Simple, solid steel. Good for prying open grates or cracking skulls."},
    {"name":"Coil Of Cable","set":"proposed","kind":"good_stuff","owner":null,"rarity":"Fine","starter":false,"count":3,"cost":0,"oomph":0,"scramble":3,"conditionalStat":false,"text":"","flavor":"High-tensile wire. Essential for rigging quick bypasses."},
    {"name":"Crowbar","set":"proposed","kind":"good_stuff","owner":null,"rarity":"Fine","starter":false,"count":3,"cost":0,"oomph":1,"scramble":1,"conditionalStat":false,"text":"Play: If you get any Good Stuff this turn, get 1 additional Good Stuff.","flavor":"Versatile tool that helps pop open supply crates."},
    {"name":"Duct Tape & Wire","set":"proposed","kind":"good_stuff","owner":null,"rarity":"Fine","starter":false,"count":3,"cost":1,"oomph":2,"scramble":2,"conditionalStat":false,"text":"","flavor":"Quick repairs that surprisingly hold together under pressure."},
    {"name":"Stim Pack","set":"proposed","kind":"good_stuff","owner":null,"rarity":"Fine","starter":false,"count":3,"cost":0,"oomph":2,"scramble":0,"conditionalStat":false,"text":"Play: Draw 1 card.","flavor":"Adrenaline surge to keep moving when stamina is low."},
    {"name":"Cutting Torch","set":"proposed","kind":"good_stuff","owner":null,"rarity":"Cool","starter":false,"count":2,"cost":2,"oomph":5,"scramble":0,"conditionalStat":false,"text":"","flavor":"Burns through reinforced bulkheads in seconds."},
    {"name":"Riot Shield","set":"proposed","kind":"good_stuff","owner":null,"rarity":"Cool","starter":false,"count":2,"cost":1,"oomph":0,"scramble":3,"conditionalStat":false,"text":"If the room is Cleared, return this card to your hand at the end of the turn.","flavor":"Heavy poly-carb barrier that survives multiple engagements."},
    {"name":"Overcharged Battery","set":"proposed","kind":"good_stuff","owner":null,"rarity":"Cool","starter":false,"count":2,"cost":1,"oomph":2,"scramble":1,"conditionalStat":false,"text":"The next card played this turn is played for free.","flavor":"Sparks fly as raw current surges through your gear."},
    {"name":"A Pair Of Stitch-Em-Ups","set":"proposed","kind":"good_stuff","owner":null,"rarity":"Cool","starter":false,"count":2,"cost":1,"oomph":0,"scramble":0,"conditionalStat":false,"text":"Choose a character. Move 2 cards from that character's Exhaust pile to the bottom of their deck.","flavor":"Field-grade medical staples to restore lost Stamina."},
    {"name":"High-Frequency Scanner","set":"proposed","kind":"good_stuff","owner":null,"rarity":"Cool","starter":false,"count":2,"cost":1,"oomph":0,"scramble":3,"conditionalStat":false,"text":"Play: Look at the top 3 cards of the Floor deck.","flavor":"Pings upcoming hazards before you step into the room."},
    {"name":"Grav Harness","set":"proposed","kind":"good_stuff","owner":null,"rarity":"Woah","starter":false,"count":1,"cost":2,"oomph":3,"scramble":3,"conditionalStat":false,"text":"One of you draws 1 card.","flavor":"Defies local gravity to make heavy obstacles weightless."},
    {"name":"Automated Salvage Kit","set":"proposed","kind":"good_stuff","owner":null,"rarity":"Woah","starter":false,"count":1,"cost":1,"oomph":2,"scramble":2,"conditionalStat":false,"text":"Play: Scrap 1 Bad Stuff card from your hand or discard pile.","flavor":"Converts toxic debris and hazards directly into usable scrap."},
    {"name":"Emergency Power Core","set":"proposed","kind":"good_stuff","owner":null,"rarity":"Woah","starter":false,"count":1,"cost":0,"oomph":3,"scramble":3,"conditionalStat":false,"text":"Exhaust 2.","flavor":"Unleashes a massive energy overload at the cost of internal circuit burning."},
    {"name":"Torn Seal","set":"proposed","kind":"bad_stuff","owner":null,"rarity":null,"starter":false,"count":2,"cost":3,"oomph":0,"scramble":0,"conditionalStat":false,"text":"","flavor":"Broken rubber gasket. Useless dead weight clogging your pack."},
    {"name":"Sluggish","set":"proposed","kind":"bad_stuff","owner":null,"rarity":null,"starter":false,"count":2,"cost":2,"oomph":0,"scramble":0,"conditionalStat":false,"text":"Holding: Cards you play cost +1 card to play.","flavor":"Limb fatigue slows down every movement."},
    {"name":"Rust","set":"proposed","kind":"bad_stuff","owner":null,"rarity":null,"starter":false,"count":2,"cost":3,"oomph":0,"scramble":0,"conditionalStat":false,"text":"Holding: Stuff cards you play have -1 Oomph and -1 Scramble.","flavor":"Corrosion degrades the quality of your scavenged gear."},
    {"name":"Faceful Of Slime","set":"proposed","kind":"bad_stuff","owner":null,"rarity":null,"starter":false,"count":2,"cost":3,"oomph":0,"scramble":0,"conditionalStat":false,"text":"Holding: At Turn Start, draw 1 fewer card.","flavor":"Murky goop blinds your vision and slows drawing."},
    {"name":"Spore Cloud","set":"proposed","kind":"bad_stuff","owner":null,"rarity":null,"starter":false,"count":2,"cost":3,"oomph":0,"scramble":0,"conditionalStat":false,"text":"Holding: At Cleanup, discard cards other than this one until you hold 3.","flavor":"Choking spores force you to drop excess gear."},
    {"name":"My Head Is Quantum Spinning","set":"proposed","kind":"bad_stuff","owner":null,"rarity":null,"starter":false,"count":2,"cost":2,"oomph":0,"scramble":0,"conditionalStat":false,"text":"Holding: Whenever your partner draws a card during Play, Exhaust 1.","flavor":"Disorientation drains stamina whenever team communication spikes."},
    {"name":"Panic","set":"proposed","kind":"bad_stuff","owner":null,"rarity":null,"starter":false,"count":2,"cost":2,"oomph":0,"scramble":0,"conditionalStat":false,"text":"Holding: Every room threshold requires +2 Scramble to be met. Play: Exhaust 2.","flavor":"Blinding fear raises room difficulty and drains team stamina."},
    {"name":"Corrosive Acid","set":"proposed","kind":"bad_stuff","owner":null,"rarity":null,"starter":false,"count":2,"cost":3,"oomph":0,"scramble":0,"conditionalStat":false,"text":"Holding: At Turn Start, Exhaust 1. Play: Scrap 1 Good Stuff card from your hand.","flavor":"Caustic fluid eats away at your deck stamina and gear."},
    {"name":"System Feedback","set":"proposed","kind":"bad_stuff","owner":null,"rarity":null,"starter":false,"count":2,"cost":2,"oomph":0,"scramble":0,"conditionalStat":false,"text":"Holding: Whenever you play a card with Cost 0, lose 1 Oomph and 1 Scramble from the Stat pool this turn.","flavor":"Electrical backlash dampens cheap card plays."}
  ],
  rooms: [
    {"name":"Security Turnstile","set":"proposed","kind":"room","band":1,"flavor":"A rusted barrier blocks the thoroughfare. You can slip through quietly or tear it off its hinges.","text":"","count":14,"challenges":[{"thresholds":[{"requires":{"oomph":0,"scramble":3},"outcome":"Clear.","clears":true,"fleeFree":false,"ascends":false,"effects":[]}]},{"thresholds":[{"requires":{"oomph":5,"scramble":0},"outcome":"Clear, and Red gets Good Stuff, but both of you Exhaust 1.","clears":true,"fleeFree":false,"ascends":false,"effects":[{"type":"TakeGoodStuff","who":"Red","count":1},{"type":"ExhaustFromDeck","who":"both","amount":1}]}]}],"flee":{"text":"Both of you Exhaust 1.","clears":false,"effects":[{"type":"ExhaustFromDeck","who":"both","amount":1}]}},
    {"name":"Flooded Ventilation Shaft","set":"proposed","kind":"room","band":1,"flavor":"A narrow duct dripping with murky condensation. Red can force the grate while Gray navigates the wiring.","text":"","count":10,"challenges":[{"thresholds":[{"requires":{"oomph":0,"scramble":4},"outcome":"Clear.","clears":true,"fleeFree":false,"ascends":false,"effects":[]}]},{"thresholds":[{"requires":{"oomph":3,"scramble":3},"outcome":"Clear, and Gray gets Good Stuff.","clears":true,"fleeFree":false,"ascends":false,"effects":[{"type":"TakeGoodStuff","who":"Gray","count":1}]}]}],"flee":{"text":"Gray Exhausts 2.","clears":false,"effects":[{"type":"ExhaustFromDeck","who":"Gray","amount":2}]}},
    {"name":"The Sentry Drone","set":"proposed","kind":"stairwell","band":1,"flavor":"An automated defense unit guarding the stairwell. Destroy its chassis or cut its power harness.","text":"","count":3,"challenges":[{"thresholds":[{"requires":{"oomph":8,"scramble":0},"outcome":"Ascend.","clears":true,"fleeFree":false,"ascends":true,"effects":[]}]},{"thresholds":[{"requires":{"oomph":0,"scramble":8},"outcome":"Ascend, and one of you gets Good Stuff.","clears":true,"fleeFree":false,"ascends":true,"effects":[{"type":"TakeGoodStuff","who":"one","count":1}]}]}],"flee":{"text":"Both of you Exhaust 1, and Red gets Bad Stuff.","clears":false,"effects":[{"type":"ExhaustFromDeck","who":"both","amount":1},{"type":"DealBadStuff","who":"Red","count":1}]}},
    {"name":"Automated Defense Turret","set":"proposed","kind":"room","band":2,"flavor":"A heavy turretted cannon sweeps the corridor. Deactivating its targeting sensors requires precision; smashing it requires brute force.","text":"","count":7,"challenges":[{"thresholds":[{"requires":{"oomph":0,"scramble":8},"outcome":"Clear, and Gray gets Good Stuff.","clears":true,"fleeFree":false,"ascends":false,"effects":[{"type":"TakeGoodStuff","who":"Gray","count":1}]}]},{"thresholds":[{"requires":{"oomph":10,"scramble":0},"outcome":"Clear, and one of you may Scrap a Bad Stuff card from your hand.","clears":true,"fleeFree":false,"ascends":false,"effects":[{"type":"ScrapBadStuffFromHand","who":"one","optional":true}]}]}],"flee":{"text":"Both of you Exhaust 2, and both of you get Bad Stuff.","clears":false,"effects":[{"type":"ExhaustFromDeck","who":"both","amount":2},{"type":"DealBadStuff","who":"both","count":1}]}},
    {"name":"Pressurized Maintenance Hub","set":"proposed","kind":"room","band":2,"flavor":"High-pressure steam pipes obstruct the gangway. Red must brace the valves while Gray hacks the overrides.","text":"","count":4,"challenges":[{"thresholds":[{"requires":{"oomph":7,"scramble":0},"outcome":"Clear, and Red reveals a card reward.","clears":true,"fleeFree":false,"ascends":false,"effects":[{"type":"RevealReward","who":"Red"}]}]},{"thresholds":[{"requires":{"oomph":0,"scramble":7},"outcome":"Clear, and Gray reveals a card reward.","clears":true,"fleeFree":false,"ascends":false,"effects":[{"type":"RevealReward","who":"Gray"}]}]}],"flee":{"text":"Both of you Exhaust 2.","clears":false,"effects":[{"type":"ExhaustFromDeck","who":"both","amount":2}]}},
    {"name":"Overgrown Hydroponics Bay","set":"proposed","kind":"room","band":2,"flavor":"Mutated flora fills the chamber, emitting dense spore clouds.","text":"","count":4,"challenges":[{"thresholds":[{"requires":{"oomph":0,"scramble":6},"outcome":"Clear, but both of you get Bad Stuff.","clears":true,"fleeFree":false,"ascends":false,"effects":[{"type":"DealBadStuff","who":"both","count":1}]}]},{"thresholds":[{"requires":{"oomph":0,"scramble":11},"outcome":"Clear, and both of you get Good Stuff.","clears":true,"fleeFree":false,"ascends":false,"effects":[{"type":"TakeGoodStuff","who":"both","count":1}]}]}],"flee":{"text":"Both of you Exhaust 2, and Gray gets Bad Stuff.","clears":false,"effects":[{"type":"ExhaustFromDeck","who":"both","amount":2},{"type":"DealBadStuff","who":"Gray","count":1}]}},
    {"name":"Gears & Glitch","set":"proposed","kind":"stairwell","band":2,"flavor":"A pair of rogue maintenance constructs blocking the stairwell door.","text":"","count":3,"challenges":[{"thresholds":[{"requires":{"oomph":12,"scramble":0},"outcome":"Ascend.","clears":true,"fleeFree":false,"ascends":true,"effects":[]}]},{"thresholds":[{"requires":{"oomph":7,"scramble":7},"outcome":"Ascend, and one of you reveals a card reward.","clears":true,"fleeFree":false,"ascends":true,"effects":[{"type":"RevealReward","who":"one"}]}]}],"flee":{"text":"Both of you Exhaust 3, and Red gets Bad Stuff.","clears":false,"effects":[{"type":"ExhaustFromDeck","who":"both","amount":3},{"type":"DealBadStuff","who":"Red","count":1}]}},
    {"name":"Laser Grid Security Hall","set":"proposed","kind":"room","band":3,"flavor":"Interlocking laser beams cover every inch of the floor. Slip through without touching a beam, or shatter the emitter relay.","text":"","count":2,"challenges":[{"thresholds":[{"requires":{"oomph":0,"scramble":14},"outcome":"Clear, and Gray reveals a card reward.","clears":true,"fleeFree":false,"ascends":false,"effects":[{"type":"RevealReward","who":"Gray"}]}]},{"thresholds":[{"requires":{"oomph":18,"scramble":0},"outcome":"Clear, but both of you Exhaust 2.","clears":true,"fleeFree":false,"ascends":false,"effects":[{"type":"ExhaustFromDeck","who":"both","amount":2}]}]}],"flee":{"text":"Both of you Exhaust 4.","clears":false,"effects":[{"type":"ExhaustFromDeck","who":"both","amount":4}]}},
    {"name":"Bio-Hazard Containment Vault","set":"proposed","kind":"room","band":3,"flavor":"A sealed vault holding experimental equipment. The door control requires an energy surge.","text":"Players may Scrap Good Stuff cards from their hand during Play to add +3 Oomph or +3 Scramble per card.","count":2,"challenges":[{"thresholds":[{"requires":{"oomph":15,"scramble":0},"outcome":"Clear, and one of you reveals a card reward.","clears":true,"fleeFree":false,"ascends":false,"effects":[{"type":"RevealReward","who":"one"}]}]},{"thresholds":[{"requires":{"oomph":0,"scramble":15},"outcome":"Clear, and one of you reveals a card reward.","clears":true,"fleeFree":false,"ascends":false,"effects":[{"type":"RevealReward","who":"one"}]}]}],"flee":{"text":"Both of you get 2 Bad Stuff, and both of you Exhaust 2.","clears":false,"effects":[{"type":"DealBadStuff","who":"both","count":2},{"type":"ExhaustFromDeck","who":"both","amount":2}]}},
    {"name":"Smoldering Armory","set":"proposed","kind":"room","band":3,"flavor":"An overheating weapons cache on the verge of exploding.","text":"","count":2,"challenges":[{"thresholds":[{"requires":{"oomph":10,"scramble":0},"outcome":"Clear, and Red gets Good Stuff.","clears":true,"fleeFree":false,"ascends":false,"effects":[{"type":"TakeGoodStuff","who":"Red","count":1}]}]},{"thresholds":[{"requires":{"oomph":16,"scramble":0},"outcome":"Clear; both of you reveal a card reward, and both of you get Good Stuff.","clears":true,"fleeFree":false,"ascends":false,"effects":[{"type":"RevealReward","who":"both"},{"type":"TakeGoodStuff","who":"both","count":1}]}]}],"flee":{"text":"Red Exhausts 5.","clears":false,"effects":[{"type":"ExhaustFromDeck","who":"Red","amount":5}]}},
    {"name":"The Iron Sentinel","set":"proposed","kind":"stairwell","band":3,"flavor":"The massive titan guarding the doorway to the upper tower.","text":"","count":3,"challenges":[{"thresholds":[{"requires":{"oomph":10,"scramble":10},"outcome":"Ascend, and both of you reveal a card reward.","clears":true,"fleeFree":false,"ascends":true,"effects":[{"type":"RevealReward","who":"both"}]}]},{"thresholds":[{"requires":{"oomph":18,"scramble":0},"outcome":"Ascend, but both of you Exhaust 3.","clears":true,"fleeFree":false,"ascends":true,"effects":[{"type":"ExhaustFromDeck","who":"both","amount":3}]}]}],"flee":{"text":"Both of you Exhaust 4, and both of you get Bad Stuff.","clears":false,"effects":[{"type":"ExhaustFromDeck","who":"both","amount":4},{"type":"DealBadStuff","who":"both","count":1}]}},
    {"name":"The Monolith Core","set":"proposed","kind":"stairwell","band":null,"flavor":"The central nexus at the apex of Pyramid Tower. It radiates crackling energy.","text":"","count":1,"challenges":[{"thresholds":[{"requires":{"oomph":10,"scramble":10},"outcome":"Ascend.","clears":true,"fleeFree":false,"ascends":true,"effects":[]}]},{"thresholds":[{"requires":{"oomph":22,"scramble":0},"outcome":"Ascend, but both of you Exhaust 3.","clears":true,"fleeFree":false,"ascends":true,"effects":[{"type":"ExhaustFromDeck","who":"both","amount":3}]}]}],"flee":{"text":"Both of you Exhaust 5.","clears":false,"effects":[{"type":"ExhaustFromDeck","who":"both","amount":5}]}}
  ],
} as const satisfies CardContent;

/** The first 12 hex of sha256 over the JSON of CARD_CONTENT above — identifies this card list. */
export const CARD_LIST_ID = "7758bd369cb1";
